In [1]:
# Text Summarizer
# Transformers is the hugging face module for transformers
!pip install transformers

Requirement already satisfied: transformers in c:\anaconda\lib\site-packages (5.12.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\anaconda\lib\site-packages (from transformers) (1.21.0)
Requirement already satisfied: numpy>=1.17 in c:\anaconda\lib\site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\anaconda\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\anaconda\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\anaconda\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\anaconda\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\anaconda\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\anaconda\lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\anaconda\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click>=8.4.0 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.10.0)
Requirement already satisfied: certifi in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\anaconda\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\anaconda\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\anaconda\lib\site-packages (from typer->transformers) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\anaconda\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: colorama in c:\anaconda\lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\anaconda\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\anaconda\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\anaconda\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: sniffio>=1.1 in c:\anaconda\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)

In [2]:
!pip install "transformers[torch]"

Requirement already satisfied: transformers[torch] in c:\anaconda\lib\site-packages (5.12.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\anaconda\lib\site-packages (from transformers[torch]) (1.21.0)
Requirement already satisfied: numpy>=1.17 in c:\anaconda\lib\site-packages (from transformers[torch]) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\anaconda\lib\site-packages (from transformers[torch]) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\anaconda\lib\site-packages (from transformers[torch]) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\anaconda\lib\site-packages (from transformers[torch]) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\anaconda\lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in c:\anaconda\lib\site-packages (from transformers[torch]) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\anaconda\lib\site-packages (from transformers[torch]) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\anaconda\lib\site-packages (from transformers[torch]) (4.67.1)
Requirement already satisfied: torch>=2.4 in c:\anaconda\lib\site-packages (from transformers[torch]) (2.12.1+cu132)
Collecting accelerate>=1.1.0 (from transformers[torch])
  Downloading accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: click>=8.4.0 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.15.0)
Requirement already satisfied: anyio in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.10.0)
Requirement already satisfied: certifi in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.11)
Requirement already satisfied: h11>=0.16 in c:\anaconda\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\anaconda\lib\site-packages (from typer->transformers[torch]) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\anaconda\lib\site-packages (from typer->transformers[torch]) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\anaconda\lib\site-packages (from typer->transformers[torch]) (0.0.4)
Requirement already satisfied: psutil in c:\anaconda\lib\site-packages (from accelerate>=1.1.0->transformers[torch]) (7.0.0)
Requirement already satisfied: colorama in c:\anaconda\lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\anaconda\lib\site-packages (from rich>=13.8.0->typer->transformers[torch]) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\anaconda\lib\site-packages (from rich>=13.8.0->typer->transformers[torch]) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\anaconda\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers[torch]) (0.1.2)
Requirement already satisfied: setuptools<82 in c:\anaconda\lib\site-packages (from torch>=2.4->transformers[torch]) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\anaconda\lib\site-packages (from torch>=2.4->transformers[torch]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\anaconda\lib\site-packages (from torch>=2.4->transformers[torch]) (3.5)
Requirement already satisfied: jinja2 in c:\anaconda\lib\site-packages (from torch>=2.4->transformers[torch]) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\anaconda\lib\site-packages (from sympy>=1.13.3->torch>=2.4->transformers[torch]) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\anaconda\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\anaconda\lib\site-packages (from jinja2->torch>=2.4->transformers[torch]) (3.0.2)
Downloading accelerate-1.14.0-py3-none-any.whl (389 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.14.0

In [1]:
import pandas as pd
from transformers import T5Tokenizer, Trainer, TrainingArguments, T5ForConditionalGeneration

In [3]:
train_data = pd.read_csv("./Dataset/samsum-train.csv")
val_data = pd.read_csv("./Dataset/samsum-validation.csv")

In [4]:
train_data.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\r\...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\r\nKim: Bad mood tbh, I wa...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\r\nSam:...,"Sam is confused, because he overheard Rick com..."

In [5]:
train_data.shape

(14732, 3)

In [6]:
# random Sampling (take only 4k samples)
train_data = train_data.sample(n=4000, random_state=42).reset_index(drop=True)
val_data = val_data.sample(n=500, random_state=42).reset_index(drop=True)

# Data Pre-Processing

In [12]:
import re

def clean_data(text):
    text = re.sub(r"\r\n", " " , text) # remove next line chars
    text = re.sub(r"\s+", " " , text) # replace all types of spaces with " "
    text = re.sub(r"<.*?>", " ", text) # remove html tags 
    text = text.strip().lower()
    return text

In [13]:
train_data["dialogue"] = train_data["dialogue"].apply(clean_data)
train_data["summary"] = train_data["summary"].apply(clean_data)

val_data["dialogue"] = val_data["dialogue"].apply(clean_data)
val_data["summary"] = val_data["summary"].apply(clean_data)

In [14]:
train_data["dialogue"][0]

"violet: hi! i came across this austin's article and i thought that you might find it interesting violet: claire: hi! :) thanks, but i've already read it. :) claire: but thanks for thinking about me :)"

# Tokenization

In [15]:
# using T5 tokenizer we get ids for words wrt the T5 pretrained model vocab
tokenizer = T5Tokenizer.from_pretrained("t5-small")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

C:\Anaconda\Lib\site-packages\huggingface_hub\file_download.py:137: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\aayus\.cache\huggingface\hub\models--t5-small. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

Error while downloading from https://huggingface.co/t5-small/resolve/main/spiece.model: The read operation timed out
Trying to resume download...

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

In [16]:
# raw data => tokenized inputs for fine-tuning
# 1. padding (adding space so that text length is standard)
# 2. max_length (define a max_length so that all the inputs are of the same len) mult of 2
# 3. truncate (cut down on extra tokens from the max_len)
def tokenize(data):
    inputs = tokenizer(data["dialogue"], padding="max_length", max_length=512, truncation=True)
    targets = tokenizer(data["summary"], padding="max_length", max_length=150, truncation=True)

    inputs['labels'] = targets['input_ids'] # token ids => add to input as labels
    return inputs

In [18]:
train_dataset = train_data.apply(tokenize, axis=1).tolist() # change to list as T5 accepts list
val_dataset = val_data.apply(tokenize, axis=1).tolist()

In [19]:
train_dataset[0]

{'input_ids': [25208, 10, 7102, 55, 3, 23, 764, 640, 48, 403, 17, 77, 31, 7, 1108, 11, 3, 23, 816, 24, 25, 429, 253, 34, 1477, 25208, 10, 3, 7997, 15, 10, 7102, 55, 3, 10, 61, 2049, 6, 68, 3, 23, 31, 162, 641, 608, 34, 5, 3, 10, 61, 3, 7997, 15, 10, 68, 2049, 21, 1631, 81, 140, 3, 10, 61, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [25208, 1622, 3, 7997, 15, 403, 17, 77, 31, 7, 1108, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [ ]:
# input ids - dialogue (tokenized and padded)
# 1 -> end of sequence EOS
# 0 -> is padding
# attention mask - tells us which values are valid and which are padding values
# labels - target (tokenized and padded)

In [21]:
len(train_dataset[0]['input_ids'])

512

# Working with Model

In [23]:
# NLP => generation task(Gen AI)
# The generation is conditional to our i/p so T5 for ConditionalGeneration
model = T5ForConditionalGeneration.from_pretrained("t5-small")

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

# Fine Tuning

In [24]:
import torch

# Change to GPU (mps - apple ; cuda - nvidia ; cpu - if nothing available)

if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print("device: " , device)
model.to(device)

device:  cuda

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=512, out_features=32128, bias=False)
)

In [25]:
# Training Arguments - refer Hugging face docs

training_args = TrainingArguments(
    output_dir='./results',   # creates checkpoints while training the model
    num_train_epochs=6,
    weight_decay=0.01,

    per_device_train_batch_size=8,   #default
    per_device_eval_batch_size=8,    #default

    eval_strategy="epoch", #eval after every epoch
    save_strategy="epoch",

    warmup_steps=500
    # learning rate grows from 0 to default value in 500 steps
)

In [26]:
# Trainer - class which provides feature complete training of Transformers
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

In [27]:
# Train the model
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=3000, training_loss=0.9064952748616536, metrics={'train_runtime': 889.7529, 'train_samples_per_second': 26.974, 'train_steps_per_second': 3.372, 'total_flos': 3248203235328000.0, 'train_loss': 0.9064952748616536, 'epoch': 6.0})

# Save the model

In [28]:
model.save_pretrained("./saved_summary_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [29]:
tokenizer.save_pretrained("./saved_summary_model")

('./saved_summary_model\\tokenizer_config.json',
 './saved_summary_model\\tokenizer.json')

In [31]:
# load model
model = T5ForConditionalGeneration.from_pretrained("./saved_summary_model")
tokenizer = T5Tokenizer.from_pretrained("./saved_summary_model")

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

# Test the Core Logic for Summarization

In [34]:
def summarize_dialogue(dialogue):
    dialogue = clean_data(dialogue) # clean 

    # tokenize
    inputs = tokenizer(
        dialogue,
        padding="max_length",
        max_length=512,
        truncation=True,
        return_tensors='pt'   # returns pytorch tensors
    ).to(device)
    
    # generate the summary (in the form of token ids)
    model.to(device)
    targets = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_length=150,
        num_beams=4,  # Beam search, i.e will generate 4 o/p and return the best one
        early_stopping=True # as soon as we get all the beams we stop
    )
    
    # convert token ids to summary (decoding)
    summary = tokenizer.decode(targets[0], skip_special_tokens=True)
    # skip_special_tokens - skips EOS and seperation tokens (SEP)

    return summary

In [35]:
test_dialogue = """ 
Reporter: In today's technology news, artificial intelligence continues to expand rapidly across industries, from healthcare to finance and education. Recent reports suggest that AI adoption has significantly increased over the past few years.

Reporter: Companies are investing heavily in machine learning systems to automate tasks, improve decision-making, and enhance customer experiences. However, this growth has also raised questions about job displacement and ethical concerns.

Expert: AI systems are becoming more capable due to advances in deep learning and access to large datasets. These models can now perform complex tasks such as language understanding, image recognition, and even code generation.

Expert: At the same time, there are valid concerns about bias in AI models, as they often reflect the data they are trained on. Ensuring fairness and transparency is becoming a key area of research.

Reporter: Governments and organizations are beginning to introduce regulations to guide the development and deployment of AI technologies. The goal is to balance innovation with accountability.

Expert: Another challenge is explainability. Many modern AI systems, especially deep neural networks, operate as “black boxes,” making it difficult to understand how decisions are made.

Reporter: Experts also highlight the importance of responsible AI development, including data privacy, security, and long-term societal impact.

Expert: Looking ahead, collaboration between researchers, policymakers, and industry leaders will be crucial to ensure that AI systems are developed and used in a safe and beneficial way.
"""

summary = summarize_dialogue(test_dialogue)

print("Summary: ", summary)

Summary:  ai adoption has significantly increased over the past few years. ai systems are becoming more capable due to advances in deep learning and access to large datasets. experts highlight the importance of responsible ai development, including data privacy, security, and long-term societal impact.